import OPERATION_TITLES from '../../constants';

const FOOTER_BY_OPERATION_TITLE = {
  [OPERATION_TITLES.EDIT_CATEGORY]: [],
  [OPERATION_TITLES.ADD_NEW_SUBCATEGORY]: [],
};

export default FOOTER_BY_OPERATION_TITLE;
